author: Cesar Figueroa
highlighter: pygments
markdown: redcarpet
permalink: /posts/:title/

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

exclude:
  - CNAME
  - Rakefile
  - Gemfile

sass:
  sass_dir: assets/stylesheets
  style: :compressed
